apiVersion: apps/v1 
kind: Deployment
metadata:
  name: api
  namespace: workshop
  labels:
    app: api
    
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api

  template: 
    metadata:
      labels: 
        app: api
    spec:
      containers: 
      - name: api
        image: 615299773556.dkr.ecr.us-east-1.amazonaws.com/backend:5
        imagePullPolicy: Always
        ports: 
        - containerPort : 3500

        env:
          - name: MONGO_CONN_STR
            value: mongodb://mongodb-svc:27017/todo?directConnection=true
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: password

        livenessProbe:
          httpGet:
            path: /ok
            port: 3500
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /ok
            port: 3500
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1


  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
