apiVersion: apps/v1 
kind: Deployment
metadata:
  name: frontend
  namespace: workshop
  labels:
    app: frontend   
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
      
  template: 
    metadata:
      name: frontend-pod
      labels: 
        app: frontend
        env: test 
    spec:
      serviceAccountName: default
      containers: 
      - name: frontend
        image: merajaprasd/three-tier-frontend
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://challenge.merajaprasad.in/api/tasks"
        ports: 
        - containerPort : 3000
        
        resources:
          requests:
            cpu: 300m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
            
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - frontend
            topologyKey: "kubernetes.io/hostname"
