apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: workshop
  labels:
    app: frontend

spec:
  type: ClusterIP
  selector:
    app: frontend

  ports:
  - protocol: TCP
    port: 3000