apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: workshop
  labels:
    app: mongodb
    
spec:
  selector:
    app: mongodb
  ports:
  - name: mongodb
    port: 27017
  clusterIP: None
